"""Pydantic schemas for race strategies and stints."""
from typing import List, Optional
from pydantic import BaseModel, Field
from src.f1_optimizer.common.schemas.race import TyreCompound


class StintPlan(BaseModel):
    """Details of a single tyre stint in a race strategy."""
    stint_number: int
    compound: TyreCompound
    start_lap: int
    end_lap: int
    stint_length: int
    predicted_stint_time: float


class PitStopDecision(BaseModel):
    """Specific pit stop event."""
    lap: int
    from_compound: TyreCompound
    to_compound: TyreCompound
    pit_cost_seconds: float


class StrategyResult(BaseModel):
    """Full strategic plan generated by an optimizer."""
    model_name: str  # "Scope 1 (MILP)" or "Scope 2 (Goal Programming)"
    total_race_time_seconds: float
    total_pit_stops: int
    pit_laps: List[int]
    stints: List[StintPlan]
    solver_status: str
    execution_time_seconds: float
    notes: Optional[str] = None
